import {getUrlKoutaBackendValintaperusteList} from '../generic/UrlStore';
import {PohjanValintaStore} from '../generic/PohjanValintaStore';
import {
  EVENT_ENTRY,
  EVENT_MODE,
  STATE_ENTRY,
  STATE_ENTRY_LIST,
  STATE_ENTRY_OPTIONS,
  STATE_MODE,
  STATE_MODE_OPTIONS
} from '../../config/scopes/PohjanValinta';
import {ENTITY_MODIFICATION_MODE} from '../../config/constants';

//TODO: yhdistetään tiloja yhden tilan alle

export const APP_STATE_VALINTAPERUSTEEN_POHJA_MODE_OPTIONS = 'APP_STATE_VALINTAPERUSTEEN_POHJA_MODE_OPTIONS';
export const APP_STATE_VALINTAPERUSTEEN_POHJA_MODE = 'APP_STATE_VALINTAPERUSTEEN_POHJA_MODE';
export const APP_EVENT_VALINTAPERUSTEEN_POHJA_MODE = 'APP_EVENT_VALINTAPERUSTEEN_POHJA_MODE';
export const APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_LIST = 'APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_LIST';
export const APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_OPTIONS = 'APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_OPTIONS';
export const APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY = 'APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY';
export const APP_EVENT_VALINTAPERUSTEEN_POHJA_ENTRY = 'APP_EVENT_VALINTAPERUSTEEN_POHJA_ENTRY';

export const SCOPE_VALINTAPERUSTEEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_VALINTAPERUSTEEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_VALINTAPERUSTEEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_VALINTAPERUSTEEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_VALINTAPERUSTEEN_POHJA_MODE
};


export const ValintaperusteenPohjaStore = () =>
  PohjanValintaStore(SCOPE_VALINTAPERUSTEEN_POHJA, getUrlKoutaBackendValintaperusteList(), getModeOptions());

const getModeOptions = () => [
  {
    label: 'Luo uusi valintaperuste',
    value: ENTITY_MODIFICATION_MODE.CREATE_ENTITY
  },
  {
    label: 'Kopioi pohjaksi aiemmin luotu valintaperuste',
    value: ENTITY_MODIFICATION_MODE.INHERIT_ENTITY
  },
  {
    label: 'Käytä olemassa olevan valintaperusteen tietoja',
    value: ENTITY_MODIFICATION_MODE.USE_ENTITY
  }
];
