env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "sqhVdXNvdFCIRxgJIotCWlxoNYLkp5kPTKPjRou7f2IvgyU30b3ZIvj3H4lrX3Pk11E5L+vQ0JE9IszuykofVEOp6Np/fGocsl5cr+dbe4ZtY6Pm3vj60C2ggZyl1xgJrDDI/c6yC1Z4xHcYv1NPRXY5aQCC0gwMzN1An6bYBwUOEM+og0M+f8Ei00cum43IU/a2+aIjRK+AbISeLaCJdDoSR8NCY9Ux2KrjgqQly7D1nkXpsEVmNcy5kQ8qiBaXAu45I3PS7+KA6TbH052J2Riuf5P88YKrHFWcrPQb/uufxKcnfGjAdmtNouUziuyxDpDFMjUm7aEOAF7Eu9ED4awUDr8Jc/Xj0vuf7Es7N3v0HVmoztYP/Uv5Tsq5G6C9qPbkgHs+kWLsVdqB7MCmK2pC/n87GAlA9mMOy31bUqaRBMJ9oJeIeSVJEC0AvHkNFpoR843A43oTo+C0GZBDTHmbnQbUd1130TUh81Gm2XO7Sr4YufV03PUB3m/XgGPEWzpIhoPXUFqP8DCPYBSiM8Aj7InejiZCSipODs5XM0F9rSd592N8J1rz1RrR0cCKJ9Tt8g8KEITdee/TGgnuuBvQ4TgObiBKydl5RAyXvENwJ9+UAO0YCgcCbHOH3jH1/yB5+FWvPNurtbuQPBnmopKlVrfcfaH73xz0SKcg1+Q="
    # AWS_SECRET_ACCESS_KEY
    - secure: "u+xoXF8x5gTRGY5EJM3Bx/FoE/ZIQDnEEycpFZbE3f6+Pom5NG6Z8KF24qKZfvRMsd3rzPfZTK9UzkNTw72848mNE72K4zyi8rz1ChG2HuAH/HCRIxhowl7FY85a+UVDTZeQ14q4mYEb0oKMY3utYYmRYa9hu6hFzt/itv/tEbUx8sDabKUXHgPaJFZ173sX4EsNbLMZZa0rYXA602E7lV06KO6/bHQlnhkncuvocjIGLeHPXVH8sG8phXArCR3Ud70bxv9o/FjZoSpwJcOLw9QSDREVJKmUnkBkQvixfUfPU8vVIywzRi8epSwRzw3hYOCyMrt6gMHNUqf+1BkIBXUBO4JulDDkdfQnyz9PnIC0nC477eAEciSo0xiAbxpO0wmHJGKRyQxXQVOL77pCynodBqIDGKmXOz/hn3e46ZyrpTefdC2qyCegoO7vNSjN3b/EAm9QvMBmK24biMEpmD/crtsQkVXAo+ZOZtSA17K0M3OMAnkdzoYjSs7h8GEcj1qPTTXWQMGuifNj8bIx1ycpGbRe+Ds9k/V+wClwPfeTJ4pdMNd1JIIBmfos7Nl+WLFNdlGJTkJZ4yFxDhecz5Q7qVCeVrnqXJOKG+7Pzp94I3jtJ5VGOGnU7Dlgrtr8JzsFoNd1JpS7TpHTJtDQOM8m4dPHgPcF5DL/reTGeBo="

jobs:
  include:
  - stage: build
    name: "Run tests"
    language: node_js
    node_js: 14
    addons:
      chrome: stable
    before_install:
      - cd src/main/app
    install:
      - npm ci --no-audit --prefer-offline
      - npm run build:test
    script:
      - npm run test:ci

  - stage: build
    name: "Run build"
    language: java
    jdk: openjdk11
    services:
      - docker
    addons:
      apt:
        packages:
          - libgconf-2-4
    cache:
      directories:
        - $HOME/.m2
      npm: true
    install:
      - git clone https://github.com/Opetushallitus/ci-tools.git
      - source ci-tools/common/setup-tools.sh
      - export ARTIFACT_NAME="kouta-ui"
    script:
      - mvn clean install

      - mv target/kouta-ui-*.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
      - cp -vr src/main/resources/* $DOCKER_BUILD_DIR/config/

      - export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
      - ./ci-tools/common/pull-image.sh
      - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME
      - ./ci-tools/build/upload-image.sh $ARTIFACT_NAME --skip-dynamo-write

  - stage: build
    name: "Publish Storybook"
    language: node_js
    node_js: 14
    install:
      - git clone https://github.com/Opetushallitus/ci-tools.git
      - source ci-tools/common/setup-tools.sh
      - export ARTIFACT_NAME="kouta-ui"
    script:
      - sh scripts/publish-storybook.sh

  - stage: deploy
    name: "Deploy container"
    script:
      - git clone https://github.com/Opetushallitus/ci-tools.git
      - source ci-tools/common/setup-tools.sh
      - export ARTIFACT_NAME="kouta-ui"
      - export BASE_IMAGE="baseimage-fatjar:master"
      - ./ci-tools/build/upload-image.sh $ARTIFACT_NAME --dynamo-write
