import { KOULUTUSTYYPPI } from '#/src/constants';

export const KOULUTUSTYYPIT_WITH_VALINTATAPA = [
  KOULUTUSTYYPPI.YLIOPISTOKOULUTUS,
  KOULUTUSTYYPPI.AMKKOULUTUS,
  KOULUTUSTYYPPI.AMMATILLINEN_OPETTAJA_ERITYISOPETTAJA_JA_OPOKOULUTUS,
];
