import {NimiStore} from '../generic/NimiStore';
import {EVENT_TRANSLATION_CHANGE, EVENT_TRANSLATION_CLEAR, STATE_TRANSLATION_MAP} from '../../config/scopes/Nimi';

export const APP_STATE_HAUN_NIMI_TRANSLATION_MAP = 'APP_STATE_HAUN_NIMI_TRANSLATION_MAP';
export const APP_EVENT_HAUN_NIMI_TRANSLATION_CHANGE = 'APP_EVENT_HAUN_NIMI_TRANSLATION_CHANGE';
export const APP_EVENT_HAUN_NIMI_TRANSLATION_CLEAR = 'APP_EVENT_HAUN_NIMI_TRANSLATION_CLEAR';

export const SCOPE_HAUN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_HAUN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_HAUN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_HAUN_NIMI_TRANSLATION_CLEAR
};

export const HaunNimiStore = () => NimiStore(SCOPE_HAUN_NIMI);
