export const APP_STATE_SECTION_EXPANSION_MAP = 'APP_STATE_SECTION EXPANSION_MAP';
export const APP_STATE_KOULUTUS_DETAILS = 'APP_STATE_KOULUTUS_DETAILS';
export const APP_STATE_ACTIVE_KOULUTUS = 'APP_STATE_ACTIVE_KOULUTUS';

export const APP_STATE_KOULUTUS_NAME_DEFAULT_TRANSLATION_MAP = 'APP_STATE_KOULUTUS_NAME_DEFAULT_TRANSLATION_MAP';
export const APP_STATE_KOULUTUS_NAME_EDITED_TRANSLATION_MAP = 'APP_STATE_KOULUTUS_NAME_EDITED_TRANSLATION_MAP';
export const APP_EVENT_KOULUTUS_NAME_EDITED_TRANSLATION_MAP = 'APP_EVENT_KOULUTUS_NAME_EDITED_TRANSLATION_MAP';

export const APP_STATE_KIELIVERSIO_OPTIONS = 'APP_STATE_KIELIVERSIO_OPTIONS';
export const APP_STATE_KIELIVERSIO_SELECTIONS = 'APP_STATE_KIELIVERSIO_SELECTIONS';
export const APP_STATE_KIELIVERSIO_SUPPORTED_LANGUAGES = 'APP_STATE_KIELIVERSIO_SUPPORTED_LANGUAGES';
export const APP_EVENT_KIELIVERSIO_SELECTION_CHANGE = 'APP_EVENT_KIELIVERSIO_SELECTION_CHANGE';
export const APP_EVENT_KIELIVERSIO_SELECTION_CLEAR = 'APP_EVENT_KIELIVERSIO_SELECTION_CLEAR';

export const APP_STATE_ORGANISAATIO_OPTIONS = 'APP_STATE_ORGANISAATIO_OPTIONS';
export const APP_STATE_ORGANISAATIO_SELECTIONS = 'APP_STATE_ORGANISAATIO_SELECTIONS';
export const APP_EVENT_ORGANISAATIO_SELECTION_CHANGE = 'APP_EVENT_ORGANISAATIO_SELECTION_CHANGE';
export const APP_EVENT_ORGANISAATIO_SELECTION_CLEAR = 'APP_EVENT_ORGANISAATIO_SELECTION_CLEAR';

export const APP_STATE_KOULUTUSKOODI_LIST = 'APP_STATE_KOULUTUSKOODI_LIST';
export const APP_STATE_KOULUTUSKOODI_LIST_IDS = 'APP_STATE_KOULUTUSKOODI_LIST.IDS';
export const APP_STATE_KOULUTUSTYYPPI_OPTIONS = 'APP_STATE_KOULUTUSTYYPPI_OPTIONS';
export const APP_STATE_ACTIVE_KOULUTUSTYYPPI_CATEGORY = 'APP_STATE_ACTIVE_KOULUTUSTYYPPI_CATEGORY';
export const APP_STATE_URL = 'APP_STATE_URL';
export const APP_STATE_WORKFLOW = 'APP_STATE_WORKFLOW';
export const APP_STATE_KOULUTUS_PERSISTENCY = 'APP_STATE_KOULUTUS_PERSISTENCY';

export const APP_STATE_KOULUTUS_LIST = 'APP_STATE_KOULUTUS_LIST';

export const APP_EVENT_SECTION_VALIDATION_REQUEST = 'APP_EVENT_SECTION_VALIDATION_REQUEST';
export const APP_EVENT_CLEAR_KOULUTUSTYYPPI_SECTION = 'APP_EVENT_CLEAR_KOULUTUSTYYPPI_SECTION';
export const APP_EVENT_SELECT_KOULUTUSTYYPPI = 'APP_EVENT_SELECT_KOULUTUSTYYPPI';
