export const APP_STATE_SECTION_EXPANSION_MAP = 'APP_STATE_SECTION EXPANSION_MAP';
export const APP_STATE_KOULUTUS_DETAILS = 'APP_STATE_KOULUTUS_DETAILS';
export const APP_STATE_ACTIVE_KOULUTUS = 'APP_STATE_ACTIVE_KOULUTUS';
export const APP_STATE_ORGANISAATIO = 'APP_STATE_ORGANISAATIO';
export const APP_STATE_ORGANISAATIO_SELECTION_MAP = '';
export const APP_STATE_KOULUTUS_LIST = 'APP_STATE_KOULUTUS_LIST';
export const APP_STATE_KOULUTUS_LIST_IDS = 'APP_STATE_KOULUTUS_LIST.IDS';
export const APP_STATE_KOULUTUSTYYPPI_OPTIONS = 'APP_STATE_KOULUTUSTYYPPI_OPTIONS';
export const APP_STATE_ACTIVE_KOULUTUSTYYPPI_CATEGORY = 'APP_STATE_ACTIVE_KOULUTUSTYYPPI_CATEGORY';
export const APP_STATE_URL = 'APP_STATE_URL';
export const APP_STATE_WORKFLOW = 'APP_STATE_WORKFLOW';
export const APP_STATE_KOULUTUS_PERSISTENCY = 'APP_STATE_KOULUTUS_PERSISTENCY';

export const APP_EVENT_SECTION_VALIDATION_REQUEST = 'APP_EVENT_SECTION_VALIDATION_REQUEST';

