export const APP_STATE_SECTION_EXPANSION_MAP = 'APP_STATE_SECTION EXPANSION_MAP';
export const APP_STATE_KOULUTUS_DETAILS = 'APP_STATE_KOULUTUS_DETAILS';
export const APP_STATE_ACTIVE_KOULUTUS = 'APP_STATE_ACTIVE_KOULUTUS';
export const APP_STATE_ORGANISAATIO = 'APP_STATE_ORGANISAATIO';
export const APP_STATE_KOULUTUS_LIST = 'APP_STATE_KOULUTUS_LIST';
export const APP_STATE_KOULUTUSTYYPPI = 'APP_STATE_KOULUTUSTYYPPI';
export const APP_STATE_URL = 'APP_STATE_URL';
