const koutaBackendDevUrl = `http://localhost:${process.env.REACT_APP_BACKEND_PORT}/kouta-backend`;

export const development = {
  'kouta-backend.base-url': 'http://localhost:' + process.env.REACT_APP_BACKEND_PORT,
  'kouta-backend.koulutus': `${koutaBackendDevUrl}/koulutus`,
  'kouta-backend.koulutus-by-oid': `${koutaBackendDevUrl}/koulutus/$1`,
  'kouta-backend.koulutus-list': `https://virkailija.untuvaopintopolku.fi/kouta-backend/koulutus/list`,
  'kouta-backend.koulutus-toteutukset': `${koutaBackendDevUrl}/koulutus/$1/toteutukset`,
  'kouta-backend.toteutus': 'http://localhost:' + process.env.REACT_APP_BACKEND_PORT + '/kouta-backend/toteutus',
  'kouta-backend.toteutus-by-oid': 'http://localhost:' + process.env.REACT_APP_BACKEND_PORT + '/kouta-backend/toteutus/$1',
  'kouta-backend.toteutus-list': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/toteutus/list',
  'kouta-backend.haku': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/haku',
  'kouta-backend.haku-by-oid': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/haku/$1',
  'kouta-backend.haku-list': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/haku/list',
  'kouta-backend.haku-hakukohteet': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/haku/$1/hakukohteet/list',
  'kouta-backend.hakukohde': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/hakukohde',
  'kouta-backend.hakukohde-by-oid': 'https://virkailija.untuvaopintopolku.fi/kouta-backend/hakukohde/$1',
  'kouta-backend.hakukohde-list': 'https://virkailija.hahtuvaopintopolku.fi/kouta-backend/hakukohde/list',
  'kouta-backend.valintaperuste': 'https://virkailija.hahtuvaopintopolku.fi/kouta-backend/valintaperuste',
  'kouta-backend.valintaperuste-by-oid': 'https://virkailija.hahtuvaopintopolku.fi/kouta-backend/valintaperuste/$1',
  'kouta-backend.valintaperuste-list': 'https://virkailija.hahtuvaopintopolku.fi/kouta-backend/valintaperuste/list',
  'kouta-backend.ammattinimike-search': `${koutaBackendDevUrl}/ammattinimike/search/$1`,
  'kouta-backend.asiasana-search': `${koutaBackendDevUrl}/asiasana/search/$1`,
  'koodisto-service.base-url': 'https://virkailija.hahtuvaopintopolku.fi/koodisto-service',
  'koodisto-service.sisaltyy-alakoodit': 'https://virkailija.hahtuvaopintopolku.fi/koodisto-service/rest/json/relaatio/sisaltyy-alakoodit/$1?koodiVersio=$2',
  'koodisto-service.sisaltyy-ylakoodit': 'https://virkailija.hahtuvaopintopolku.fi/koodisto-service/rest/json/relaatio/sisaltyy-ylakoodit/$1',
  'koodisto-service.koodi': 'https://virkailija.hahtuvaopintopolku.fi/koodisto-service/rest/json/$1/koodi?onlyValidKoodis=true',
  'koodisto-service.codeelement': 'https://virkailija.hahtuvaopintopolku.fi/koodisto-service/rest/codeelement/$1',
  'eperusteet-service.base-url': 'https://virkailija.hahtuvaopintopolku.fi/eperusteet-service',
  'eperusteet-service.perusteet-koulutuskoodilla': 'https://virkailija.hahtuvaopintopolku.fi/eperusteet-service/api/perusteet?tuleva=true&siirtyma=false&voimassaolo=true&poistunut=false&kieli=fi&koulutuskoodi=$1',
  'eperusteet-service.osaamisalakuvaukset': 'https://virkailija.hahtuvaopintopolku.fi/eperusteet-service/api/perusteet/$1/osaamisalakuvaukset',
  'organisaatio-service.base-url': 'https://virkailija.hahtuvaopintopolku.fi/organisaatio-service',
  'organisaatio-service.children': 'https://virkailija.hahtuvaopintopolku.fi/organisaatio-service/rest/organisaatio/v4/$1/children?includeImage=false',
  'organisaatio-service.hierarkia': 'https://virkailija.hahtuvaopintopolku.fi/organisaatio-service/rest/organisaatio/v4/hierarkia/hae?oid=$1&aktiiviset=true&suunnitellut=true&lakkautetut=false',
  'organisaatio-service.organisaatio-by-oid': 'https://virkailija.hahtuvaopintopolku.fi/organisaatio-service/rest/organisaatio/v4/$1?includeImage=false',
  'lokalisaatio-service.localisation': 'https://virkailija.hahtuvaopintopolku.fi/lokalisointi/cxf/rest/v1/localisation?category=$1',
};
