import {NimiStore} from '../generic/NimiStore';
import {EVENT_TRANSLATION_CHANGE, EVENT_TRANSLATION_CLEAR, STATE_TRANSLATION_MAP} from '../../config/scopes/Nimi';
import {handleEvent, updateState} from '../../utils/stateUtils';
import {APP_STATE_KOULUTUKSEN_TIEDOT} from './KoulutuksenTiedotStore';

export const APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP = 'APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP';
export const APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE = 'APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE';
export const APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR = 'APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR';

export const SCOPE_KOULUTUKSEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR
};

export const KoulutuksenNimiStore = () => {
  NimiStore(SCOPE_KOULUTUKSEN_NIMI);
  handleEvent(APP_STATE_KOULUTUKSEN_TIEDOT, (details) => configureTranslationMap(details.nameTranslationMap));
};

const configureTranslationMap = (translationMap) =>
  updateState(APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP, translationMap);
