import {getUrlKoutaBackendHakukohdeList} from '../generic/UrlStore';
import {PohjanValintaStore} from '../generic/PohjanValintaStore';
import {EVENT_ENTRY, EVENT_MODE, STATE_ENTRY, STATE_ENTRY_LIST, STATE_ENTRY_OPTIONS, STATE_MODE, STATE_MODE_OPTIONS} from '../../config/scopes/PohjanValinta';
import {ENTITY_MODIFICATION_MODE} from '../../config/constants';
import {
  APP_EVENT_HAKUKOHTEEN_POHJA_ENTRY,
  APP_STATE_HAKUKOHTEEN_POHJA_ENTRY,
  APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_LIST,
  APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_OPTIONS
} from '../../config/states';

export const APP_STATE_HAKUKOHTEEN_POHJA_MODE_OPTIONS = 'APP_STATE_HAKUKOHTEEN_POHJA_MODE_OPTIONS';
export const APP_STATE_HAKUKOHTEEN_POHJA_MODE = 'APP_STATE_HAKUKOHTEEN_POHJA_MODE';
export const APP_EVENT_HAKUKOHTEEN_POHJA_MODE = 'APP_EVENT_HAKUKOHTEEN_POHJA_MODE';

export const SCOPE_HAKUKOHTEEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_HAKUKOHTEEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_HAKUKOHTEEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_HAKUKOHTEEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_HAKUKOHTEEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_HAKUKOHTEEN_POHJA_MODE
};

export const HakukohteenPohjaStore = () =>
  PohjanValintaStore(SCOPE_HAKUKOHTEEN_POHJA, getUrlKoutaBackendHakukohdeList(), getModeOptions());

const getModeOptions = () => [
  {
    label: 'Luo uusi hakukohde',
    value: ENTITY_MODIFICATION_MODE.CREATE_ENTITY
  },
  {
    label: 'Kopioi pohjaksi aiemmin luotu hakukohde',
    value: ENTITY_MODIFICATION_MODE.INHERIT_ENTITY
  },
  {
    label: 'Käytä olemassa olevan hakukohteen tietoja',
    value: ENTITY_MODIFICATION_MODE.USE_ENTITY
  }
];
