import {NimiStore} from '../generic/NimiStore';
import {EVENT_TRANSLATION_CHANGE, EVENT_TRANSLATION_CLEAR, STATE_TRANSLATION_MAP} from '../../config/scopes/Nimi';
import {
  APP_EVENT_HAKUKOHTEEN_NIMI_TRANSLATION_CHANGE,
  APP_EVENT_HAKUKOHTEEN_NIMI_TRANSLATION_CLEAR,
  APP_STATE_HAKUKOHTEEN_NIMI_TRANSLATION_MAP
} from '../../config/states';

export const SCOPE_HAKUKOHTEEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_HAKUKOHTEEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_HAKUKOHTEEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_HAKUKOHTEEN_NIMI_TRANSLATION_CLEAR
};

export const HakukohteenNimiStore = () => NimiStore(SCOPE_HAKUKOHTEEN_NIMI);

