import {PohjanValintaStore} from '../generic/PohjanValintaStore';
import {EVENT_ENTRY, EVENT_MODE, STATE_ENTRY, STATE_ENTRY_LIST, STATE_ENTRY_OPTIONS, STATE_MODE, STATE_MODE_OPTIONS} from '../../config/scopes/PohjanValinta';
import {ENTITY_MODIFICATION_MODE} from '../../config/constants';
import {urls} from "oph-urls-js";

export const APP_STATE_TOTEUTUKSEN_POHJA_MODE_OPTIONS = 'APP_STATE_TOTEUTUKSEN_POHJA_MODE_OPTIONS';
export const APP_STATE_TOTEUTUKSEN_POHJA_MODE = 'APP_STATE_TOTEUTUKSEN_POHJA_MODE';
export const APP_EVENT_TOTEUTUKSEN_POHJA_MODE = 'APP_EVENT_TOTEUTUKSEN_POHJA_MODE';
export const APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_LIST = 'APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_LIST';
export const APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_OPTIONS = 'APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_OPTIONS';
export const APP_STATE_TOTEUTUKSEN_POHJA_ENTRY = 'APP_STATE_TOTEUTUKSEN_POHJA_ENTRY';
export const APP_EVENT_TOTEUTUKSEN_POHJA_ENTRY = 'APP_EVENT_TOTEUTUKSEN_POHJA_ENTRY';

export const SCOPE_TOTEUTUKSEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_TOTEUTUKSEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_TOTEUTUKSEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_TOTEUTUKSEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_TOTEUTUKSEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_TOTEUTUKSEN_POHJA_MODE
};


export const ToteutuksenPohjaStore = () =>
  PohjanValintaStore(SCOPE_TOTEUTUKSEN_POHJA, urls.url('kouta-backend.toteutus-list'), getModeOptions());

const getModeOptions = () => [
  {
    label: 'Luo uusi toteutus',
    value: ENTITY_MODIFICATION_MODE.CREATE_ENTITY
  },
  {
    label: 'Kopioi pohjaksi aiemmin luotu toteutus',
    value: ENTITY_MODIFICATION_MODE.INHERIT_ENTITY
  },
  {
    label: 'Käytä olemassa olevan toteutuksen tietoja',
    value: ENTITY_MODIFICATION_MODE.USE_ENTITY
  }
];
