export const STATE_OPTIONS = 'STATE_OPTIONS';
export const STATE_SELECTIONS = 'STATE_SELECTIONS';
export const STATE_SUPPORTED_LANGUAGES = 'STATE_SUPPORTED_LANGUAGES';
export const EVENT_SELECTION_CHANGE = 'EVENT_SELECTION_CHANGE';
export const EVENT_SELECTION_CLEAR = 'EVENT_SELECTION_CLEAR';
