import {
  APP_EVENT_HAKUKOHTEEN_KIELIVERSIO_SELECTION_CHANGE,
  APP_EVENT_HAKUKOHTEEN_KIELIVERSIO_SELECTION_CLEAR,
  APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CHANGE,
  APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CLEAR,
  APP_EVENT_VALINTAPERUSTEEN_KIELIVERSIO_SELECTION_CHANGE,
  APP_EVENT_VALINTAPERUSTEEN_KIELIVERSIO_SELECTION_CLEAR,
  APP_STATE_HAKUKOHTEEN_KIELIVERSIO_OPTIONS,
  APP_STATE_HAKUKOHTEEN_KIELIVERSIO_SELECTIONS,
  APP_STATE_HAKUKOHTEEN_KIELIVERSIO_SUPPORTED_LANGUAGES,
  APP_STATE_HAUN_KIELIVERSIO_OPTIONS,
  APP_STATE_HAUN_KIELIVERSIO_SELECTIONS,
  APP_STATE_HAUN_KIELIVERSIO_SUPPORTED_LANGUAGES,
  APP_STATE_VALINTAPERUSTEEN_KIELIVERSIO_OPTIONS,
  APP_STATE_VALINTAPERUSTEEN_KIELIVERSIO_SELECTIONS,
  APP_STATE_VALINTAPERUSTEEN_KIELIVERSIO_SUPPORTED_LANGUAGES
} from '../states';

export const STATE_OPTIONS = 'STATE_OPTIONS';
export const STATE_SELECTIONS = 'STATE_SELECTIONS';
export const STATE_SUPPORTED_LANGUAGES = 'STATE_SUPPORTED_LANGUAGES';
export const EVENT_SELECTION_CHANGE = 'EVENT_SELECTION_CHANGE';
export const EVENT_SELECTION_CLEAR = 'EVENT_SELECTION_CLEAR';

export const SCOPE_HAUN_KIELIVERSIO = {
  [STATE_OPTIONS]: APP_STATE_HAUN_KIELIVERSIO_OPTIONS,
  [STATE_SELECTIONS]: APP_STATE_HAUN_KIELIVERSIO_SELECTIONS,
  [STATE_SUPPORTED_LANGUAGES]: APP_STATE_HAUN_KIELIVERSIO_SUPPORTED_LANGUAGES,
  [EVENT_SELECTION_CHANGE]: APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CHANGE,
  [EVENT_SELECTION_CLEAR]: APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CLEAR
};

export const SCOPE_HAKUKOHTEEN_KIELIVERSIO = {
  [STATE_OPTIONS]: APP_STATE_HAKUKOHTEEN_KIELIVERSIO_OPTIONS,
  [STATE_SELECTIONS]: APP_STATE_HAKUKOHTEEN_KIELIVERSIO_SELECTIONS,
  [STATE_SUPPORTED_LANGUAGES]: APP_STATE_HAKUKOHTEEN_KIELIVERSIO_SUPPORTED_LANGUAGES,
  [EVENT_SELECTION_CHANGE]: APP_EVENT_HAKUKOHTEEN_KIELIVERSIO_SELECTION_CHANGE,
  [EVENT_SELECTION_CLEAR]: APP_EVENT_HAKUKOHTEEN_KIELIVERSIO_SELECTION_CLEAR
};

export const SCOPE_VALINTAPERUSTEEN_KIELIVERSIO = {
  [STATE_OPTIONS]: APP_STATE_VALINTAPERUSTEEN_KIELIVERSIO_OPTIONS,
  [STATE_SELECTIONS]: APP_STATE_VALINTAPERUSTEEN_KIELIVERSIO_SELECTIONS,
  [STATE_SUPPORTED_LANGUAGES]: APP_STATE_VALINTAPERUSTEEN_KIELIVERSIO_SUPPORTED_LANGUAGES,
  [EVENT_SELECTION_CHANGE]: APP_EVENT_VALINTAPERUSTEEN_KIELIVERSIO_SELECTION_CHANGE,
  [EVENT_SELECTION_CLEAR]: APP_EVENT_VALINTAPERUSTEEN_KIELIVERSIO_SELECTION_CLEAR
};
