//TODO: puretaan kaikki scopet

export const STATE_TRANSLATION_MAP = 'STATE_TRANSLATION_MAP';
export const EVENT_TRANSLATION_CHANGE = 'EVENT_TRANSLATION_CHANGE';
export const EVENT_TRANSLATION_CLEAR = 'EVENT_TRANSLATION_CLEAR';


