import {
  APP_EVENT_HAUN_NIMI_TRANSLATION_CHANGE,
  APP_EVENT_HAUN_NIMI_TRANSLATION_CLEAR,
  APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE,
  APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR,
  APP_EVENT_TOTEUTUKSEN_NIMI_TRANSLATION_CHANGE,
  APP_EVENT_TOTEUTUKSEN_NIMI_TRANSLATION_CLEAR,
  APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CHANGE,
  APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CLEAR,
  APP_STATE_HAUN_NIMI_TRANSLATION_MAP,
  APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP,
  APP_STATE_TOTEUTUKSEN_NIMI_TRANSLATION_MAP,
  APP_STATE_VALINTAPERUSTEEN_NIMI_TRANSLATION_MAP
} from '../states';

export const STATE_TRANSLATION_MAP = 'STATE_TRANSLATION_MAP';
export const EVENT_TRANSLATION_CHANGE = 'EVENT_TRANSLATION_CHANGE';
export const EVENT_TRANSLATION_CLEAR = 'EVENT_TRANSLATION_CLEAR';

export const SCOPE_KOULUTUKSEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR
};

export const SCOPE_TOTEUTUKSEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_TOTEUTUKSEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_TOTEUTUKSEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_TOTEUTUKSEN_NIMI_TRANSLATION_CLEAR
};
export const SCOPE_HAUN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_HAUN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_HAUN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_HAUN_NIMI_TRANSLATION_CLEAR
};

export const SCOPE_VALINTAPERUSTEEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_VALINTAPERUSTEEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CLEAR
};
