import {
  APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE,
  APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR,
  APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP
} from '../states';

//TODO: puretaan kaikki scopet

export const STATE_TRANSLATION_MAP = 'STATE_TRANSLATION_MAP';
export const EVENT_TRANSLATION_CHANGE = 'EVENT_TRANSLATION_CHANGE';
export const EVENT_TRANSLATION_CLEAR = 'EVENT_TRANSLATION_CLEAR';

export const SCOPE_KOULUTUKSEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_KOULUTUKSEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_KOULUTUKSEN_NIMI_TRANSLATION_CLEAR
};


