import {
  APP_EVENT_HAKUKOHTEEN_POHJA_ENTRY,
  APP_EVENT_HAKUKOHTEEN_POHJA_MODE,
  APP_EVENT_KOULUTUKSEN_POHJA_ENTRY,
  APP_EVENT_KOULUTUKSEN_POHJA_MODE,
  APP_EVENT_TOTEUTUKSEN_POHJA_ENTRY,
  APP_EVENT_TOTEUTUKSEN_POHJA_MODE,
  APP_EVENT_VALINTAPERUSTEEN_POHJA_ENTRY,
  APP_EVENT_VALINTAPERUSTEEN_POHJA_MODE,
  APP_STATE_HAKUKOHTEEN_POHJA_ENTRY,
  APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_LIST,
  APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_OPTIONS,
  APP_STATE_HAKUKOHTEEN_POHJA_MODE,
  APP_STATE_HAKUKOHTEEN_POHJA_MODE_OPTIONS,
  APP_STATE_KOULUTUKSEN_POHJA_ENTRY,
  APP_STATE_KOULUTUKSEN_POHJA_ENTRY_LIST,
  APP_STATE_KOULUTUKSEN_POHJA_ENTRY_OPTIONS,
  APP_STATE_KOULUTUKSEN_POHJA_MODE,
  APP_STATE_KOULUTUKSEN_POHJA_MODE_OPTIONS,
  APP_STATE_TOTEUTUKSEN_POHJA_ENTRY,
  APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_LIST,
  APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_OPTIONS,
  APP_STATE_TOTEUTUKSEN_POHJA_MODE,
  APP_STATE_TOTEUTUKSEN_POHJA_MODE_OPTIONS,
  APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY,
  APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_LIST,
  APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_OPTIONS,
  APP_STATE_VALINTAPERUSTEEN_POHJA_MODE,
  APP_STATE_VALINTAPERUSTEEN_POHJA_MODE_OPTIONS
} from '../states';

export const STATE_ENTRY_LIST = 'STATE_ENTRY_LIST';
export const STATE_ENTRY_OPTIONS = 'STATE_ENTRY_OPTIONS';
export const STATE_MODE = 'STATE_MODE';
export const STATE_MODE_OPTIONS = 'STATE_MODE_OPTIONS';
export const STATE_ENTRY = 'STATE_ENTRY';
export const EVENT_ENTRY = 'EVENT_ENTRY';
export const EVENT_MODE = 'EVENT_MODE';

// TODO: move all scopes to corresponding stores, maybe purge all scopes for code readability (?)

export const SCOPE_KOULUTUKSEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_KOULUTUKSEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_KOULUTUKSEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_KOULUTUKSEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_KOULUTUKSEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_KOULUTUKSEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_KOULUTUKSEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_KOULUTUKSEN_POHJA_MODE
};

export const SCOPE_TOTEUTUKSEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_TOTEUTUKSEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_TOTEUTUKSEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_TOTEUTUKSEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_TOTEUTUKSEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_TOTEUTUKSEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_TOTEUTUKSEN_POHJA_MODE
};

export const SCOPE_HAKUKOHTEEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_HAKUKOHTEEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_HAKUKOHTEEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_HAKUKOHTEEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_HAKUKOHTEEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_HAKUKOHTEEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_HAKUKOHTEEN_POHJA_MODE
};

export const SCOPE_VALINTAPERUSTEEN_POHJA = {
  [STATE_ENTRY_LIST]: APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_LIST,
  [STATE_ENTRY_OPTIONS]: APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY_OPTIONS,
  [STATE_MODE]: APP_STATE_VALINTAPERUSTEEN_POHJA_MODE,
  [STATE_MODE_OPTIONS]: APP_STATE_VALINTAPERUSTEEN_POHJA_MODE_OPTIONS,
  [STATE_ENTRY]: APP_STATE_VALINTAPERUSTEEN_POHJA_ENTRY,
  [EVENT_ENTRY]: APP_EVENT_VALINTAPERUSTEEN_POHJA_ENTRY,
  [EVENT_MODE]: APP_EVENT_VALINTAPERUSTEEN_POHJA_MODE
};

