import {EVENT_SELECTION_CHANGE, EVENT_SELECTION_CLEAR, STATE_OPTIONS, STATE_SELECTIONS, STATE_SUPPORTED_LANGUAGES} from '../../config/scopes/Kieliversio';
import {getSupportedLanguagesInScope, KieliversioStore} from '../generic/KieliversioStore';

export const APP_STATE_HAUN_KIELIVERSIO_OPTIONS = 'APP_STATE_HAUN_KIELIVERSIO_OPTIONS';
export const APP_STATE_HAUN_KIELIVERSIO_SELECTIONS = 'APP_STATE_HAUN_KIELIVERSIO_SELECTIONS';
export const APP_STATE_HAUN_KIELIVERSIO_SUPPORTED_LANGUAGES = 'APP_STATE_HAUN_KIELIVERSIO_SUPPORTED_LANGUAGES';
export const APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CHANGE = 'APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CHANGE';
export const APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CLEAR = 'APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CLEAR';

export const SCOPE_HAUN_KIELIVERSIO = {
  [STATE_OPTIONS]: APP_STATE_HAUN_KIELIVERSIO_OPTIONS,
  [STATE_SELECTIONS]: APP_STATE_HAUN_KIELIVERSIO_SELECTIONS,
  [STATE_SUPPORTED_LANGUAGES]: APP_STATE_HAUN_KIELIVERSIO_SUPPORTED_LANGUAGES,
  [EVENT_SELECTION_CHANGE]: APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CHANGE,
  [EVENT_SELECTION_CLEAR]: APP_EVENT_HAUN_KIELIVERSIO_SELECTION_CLEAR
};

export const HaunKieliversioStore = () => KieliversioStore(SCOPE_HAUN_KIELIVERSIO);

export const getSupportedLanguages = () => getSupportedLanguagesInScope(SCOPE_HAUN_KIELIVERSIO);
