import {NimiStore} from '../generic/NimiStore';
import {EVENT_TRANSLATION_CHANGE, EVENT_TRANSLATION_CLEAR, STATE_TRANSLATION_MAP} from '../../config/scopes/Nimi';

export const APP_STATE_VALINTAPERUSTEEN_NIMI_TRANSLATION_MAP = 'APP_STATE_VALINTAPERUSTEEN_NIMI_TRANSLATION_MAP';
export const APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CHANGE = 'APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CHANGE';
export const APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CLEAR = 'APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CLEAR';

export const SCOPE_VALINTAPERUSTEEN_NIMI = {
  [STATE_TRANSLATION_MAP]: APP_STATE_VALINTAPERUSTEEN_NIMI_TRANSLATION_MAP,
  [EVENT_TRANSLATION_CHANGE]: APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CHANGE,
  [EVENT_TRANSLATION_CLEAR]: APP_EVENT_VALINTAPERUSTEEN_NIMI_TRANSLATION_CLEAR
};

export const ValintaperusteenNimiStore = () => NimiStore(SCOPE_VALINTAPERUSTEEN_NIMI);
